Spring:
  datasource:
    url: ${AWS_RDS_DEV}
    username: ${AWS_RDS_DEV_USERNAME}
    password: ${AWS_RDS_DEV_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis ??
mybatis:
  # ??????? ?? ??? ??? ? ??? ??? ???????, ??? ???? ??? ?? ?? ??
  type-aliases-package: com.pickple.batch
  # underscore? camel-case ?? ??
  configuration:
    map-underscore-to-camel-case: true
  # mapper?? xml??? ???? ????? ??
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: com.pickple.batch

